"""
backend/routers/reports.py
──────────────────────────
Report listing + export.

    GET /reports            -> list all generated reports
Loads both in-memory reports and persisted outputs/report_*.json files
generated by completed scans. Combines discovery data (crawl JSON) and
heuristic analysis (report JSON) into complete, structured reports.

Endpoints:
    GET /reports            -> list all reports with full findings
    GET /reports/{id}       -> get a single report
    GET /reports/{id}/export -> download a report as JSON
"""

import json

import os
import time
from datetime import datetime
from pathlib import Path
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from store import Report, reports
import config
from store import reports as memory_reports

router = APIRouter(prefix="/reports", tags=["reports"])


@router.get("", response_model=list[Report])
def _format_finding(item: dict, default_agent: str = "Crawler") -> dict:
    """Normalize finding dictionaries into the standard UI schema."""
    vuln_name = item.get("vulnerability") or item.get("issue") or item.get("title") or "Security Finding"
    endpoint = item.get("endpoint") or item.get("url") or item.get("source") or "Global"
    
    # Infer severity if not explicitly provided
    sev = item.get("severity", "").upper()
    if not sev:
        lower_name = vuln_name.lower()
        if any(k in lower_name for k in ["sql", "command", "rce", "remote code", "ssrf"]):
            sev = "HIGH"
        elif any(k in lower_name for k in ["xss", "csrf", "authorization", "auth", "idor", "upload"]):
            sev = "MEDIUM"
        elif any(k in lower_name for k in ["header", "tls", "cookie", "leak", "cors"]):
            sev = "LOW"
        else:
            sev = "INFO"
            
    # Infer agent
    agent = item.get("agent")
    if not agent:
        lower_name = vuln_name.lower()
        if "sql" in lower_name and "nosql" not in lower_name:
            agent = "SQL Agent"
        elif "nosql" in lower_name:
            agent = "NoSQL Agent"
        elif "xss" in lower_name:
            agent = "XSS Agent"
        elif "ssrf" in lower_name:
            agent = "SSRF Agent"
        elif "authorization" in lower_name or "authz" in lower_name:
            agent = "AuthZ Agent"
        elif "password" in lower_name:
            agent = "Password Policy Agent"
        elif "upload" in lower_name:
            agent = "Upload Agent"
        elif "idor" in lower_name:
            agent = "IDOR Agent"
        elif "header" in lower_name or "sensitive" in lower_name:
            agent = "SAST Agent"
        else:
            agent = default_agent

    detail = item.get("detail") or item.get("validation") or item.get("content") or "Detected during security discovery."
    if isinstance(detail, list):
        detail = ", ".join(str(x) for x in detail)

    return {
        "severity": sev,
        "title": vuln_name,
        "endpoint": str(endpoint),
        "agent": agent,
        "detail": str(detail),
    }


def load_all_persisted_reports() -> list[dict]:
    """Scan outputs directory for all report_*.json files and load findings."""
    all_reports: list[dict] = []
    seen_ids = set()

    output_dir = Path(config.OUTPUT_DIR)
    if not output_dir.exists():
        return []

    # Sort report files by modification time (newest first)
    report_files = sorted(
        output_dir.glob("report_*.json"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )

    for r_path in report_files:
        try:
            with open(r_path, "r", encoding="utf-8") as f:
                r_data = json.load(f)
        except Exception:
            continue

        # e.g. report_job_2_396127.json -> job_2_396127
        file_stem = r_path.stem
        job_id = file_stem.replace("report_", "")
        rpt_id = f"RPT-{job_id[-6:].upper()}" if len(job_id) >= 6 else f"RPT-{job_id.upper()}"
        seen_ids.add(rpt_id)

        mtime = r_path.stat().st_mtime
        dt = datetime.fromtimestamp(mtime)
        date_str = dt.strftime("%b %d, %Y")
        time_str = dt.strftime("%I:%M %p")

        target = r_data.get("target") or "Unknown Target"
        summary = r_data.get("summary", {})
        statistics = r_data.get("statistics", {})
        raw_vulns = r_data.get("potential_vulnerabilities", [])

        # Load matching crawl file if available for extra recon details
        crawl_path = output_dir / f"crawl_{job_id}.json"
        crawl_data = {}
        if crawl_path.exists():
            try:
                with open(crawl_path, "r", encoding="utf-8") as cf:
                    crawl_data = json.load(cf)
            except Exception:
                crawl_data = {}

        findings: list[dict] = []

        # 1. Potential vulnerabilities from ContextBuilder / DeepHat
        for v in raw_vulns:
            findings.append(_format_finding(v))

        # 2. Header issues from crawl
        for h in crawl_data.get("header_audit", []):
            findings.append(_format_finding(h, default_agent="SAST Agent"))

        # 3. TLS findings
        for t in crawl_data.get("tls_findings", []):
            findings.append(_format_finding(t, default_agent="SAST Agent"))

        # 4. Secrets exposed
        for s in crawl_data.get("secrets", []):
            findings.append({
                "severity": "HIGH" if any(k in s.get("type", "").lower() for k in ["key", "secret", "token", "password"]) else "MEDIUM",
                "title": f"Exposed Secret: {s.get('type', 'Unknown')}",
                "endpoint": s.get("source", target),
                "agent": "SAST Agent",
                "detail": f"Content: {s.get('content', '')[:120]}",
            })

        # 5. Sensitive files
        for sf in crawl_data.get("sensitive_files", []):
            findings.append({
                "severity": "HIGH",
                "title": "Sensitive File Disclosed",
                "endpoint": str(sf),
                "agent": "SAST Agent",
                "detail": "Sensitive configuration or backup file identified on target.",
            })

        # Calculate counts
        high_cnt = sum(1 for x in findings if x["severity"] == "HIGH")
        med_cnt = sum(1 for x in findings if x["severity"] == "MEDIUM")
        low_cnt = sum(1 for x in findings if x["severity"] == "LOW")
        info_cnt = sum(1 for x in findings if x["severity"] == "INFO")

        # Estimate duration
        duration_sec = 45
        if crawl_path.exists():
            diff = abs(r_path.stat().st_mtime - crawl_path.stat().st_mtime)
            if diff > 0:
                duration_sec = max(5, int(diff))
        mins, secs = divmod(duration_sec, 60)
        duration_str = f"{mins}m {secs}s" if mins else f"{secs}s"

        all_reports.append({
            "id": rpt_id,
            "job_id": job_id,
            "target": target,
            "date": date_str,
            "time": time_str,
            "duration": duration_str,
            "status": "complete",
            "high": high_cnt,
            "medium": med_cnt,
            "low": low_cnt,
            "info": info_cnt,
            "findings": findings,
            "summary": summary,
            "tech_stack": crawl_data.get("summary", {}).get("tech_stack", []) or crawl_data.get("tech_stack", []),
            "execution_plan": r_data.get("execution_plan", []),
        })

    return all_reports


@router.get("", response_model=list[dict])
async def list_reports():
    return list(reports.values())
    """Returns all scan reports with structured findings."""
    persisted = load_all_persisted_reports()
    if persisted:
        return persisted

    # Fallback to memory reports if no disk files yet
    results = []
    for r in memory_reports.values():
        results.append({
            "id": r.id,
            "job_id": r.scan_id,
            "target": r.title.replace("Scan report — ", ""),
            "date": datetime.fromtimestamp(r.created_at).strftime("%b %d, %Y"),
            "time": datetime.fromtimestamp(r.created_at).strftime("%I:%M %p"),
            "duration": "1m 15s",
            "status": "complete",
            "high": 1,
            "medium": 2,
            "low": 1,
            "info": 0,
            "findings": [],
            "summary": {"summary_text": r.summary},
            "tech_stack": [],
            "execution_plan": [],
        })
    return results


@router.get("/{report_id}")
async def get_report(report_id: str):
    reports = load_all_persisted_reports()
    for r in reports:
        if r["id"] == report_id or r.get("job_id") == report_id:
            return r
    raise HTTPException(status_code=404, detail="report not found")


@router.get("/{report_id}/export")
async def export_report(report_id: str):
    all_reports = load_all_persisted_reports()
    match = next((r for r in all_reports if r["id"] == report_id or r.get("job_id") == report_id), None)
    if match is None:
        raise HTTPException(status_code=404, detail="report not found")

    payload = json.dumps(match, indent=2)
    return StreamingResponse(
        iter([payload]),
        media_type="application/json",
        headers={"Content-Disposition": f'attachment; filename="{report_id}.json"'},
    )
