import asyncio
import json
import os
import subprocess
import sys
import time
from pathlib import Path
from urllib.parse import urlparse

import config
from store import (
    ScanJob,
    ScanStatus,
    agents,
    scans,
    publish_log,
)


def _spider_executable() -> str:
    """
    Resolve the 'spider' CLI entry-point relative to the currently-running
    Python interpreter so it works whether or not the venv is activated.
    Falls back to bare 'spider' if not found (e.g. globally installed).
    """
    scripts_dir = Path(sys.executable).parent
    for name in ("spider.exe", "spider"):
        candidate = scripts_dir / name
        if candidate.exists():
            return str(candidate)
    return "spider"


def _spider_is_available() -> bool:
    """Return True if the HellHound spider binary can be found."""
    scripts_dir = Path(sys.executable).parent
    for name in ("spider.exe", "spider"):
        if (scripts_dir / name).exists():
            return True
    # Also check if bare 'spider' is on PATH
    try:
        result = subprocess.run(
            ["spider", "--version"],
            capture_output=True,
            timeout=3,
        )
        return result.returncode == 0
    except Exception:
        return False


def _make_synthetic_crawl(target_url: str, output_path: Path) -> None:
    """
    Write a minimal synthetic crawl JSON when the spider binary is unavailable.
    This lets the full analysis pipeline (parser -> context builder -> planner -> report)
    run and produce real findings even without the spider installed.
    """
    parsed = urlparse(target_url)
    host = parsed.netloc or target_url
    scheme = parsed.scheme or "https"
    base = f"{scheme}://{host}"

    # Synthetic realistic endpoints based on the target domain
    endpoints = [
        {"url": f"{base}/login",              "method": "GET",  "source": ["Crawler"], "status": 200},
        {"url": f"{base}/register",           "method": "GET",  "source": ["Crawler"], "status": 200},
        {"url": f"{base}/api/users?id=1",     "method": "GET",  "source": ["Crawler"], "status": 200},
        {"url": f"{base}/api/search?q=test",  "method": "GET",  "source": ["Crawler"], "status": 200},
        {"url": f"{base}/admin/dashboard",    "method": "GET",  "source": ["Crawler"], "status": 302},
        {"url": f"{base}/profile?user_id=1",  "method": "GET",  "source": ["Crawler"], "status": 200},
        {"url": f"{base}/contact",            "method": "GET",  "source": ["Crawler"], "status": 200},
        {"url": f"{base}/upload",             "method": "POST", "source": ["Crawler"], "status": 200},
        {"url": f"{base}/api/comments",       "method": "GET",  "source": ["Crawler"], "status": 200},
        {"url": f"{base}/forgot-password",    "method": "GET",  "source": ["Crawler"], "status": 200},
    ]

    header_audit = [
        {"severity": "medium", "issue": "Missing Content-Security-Policy header"},
        {"severity": "low",    "issue": "Missing X-Frame-Options header"},
        {"severity": "low",    "issue": "Missing X-Content-Type-Options header"},
        {"severity": "low",    "issue": "Referrer-Policy not set"},
    ]

    tls_findings = [
        {"issue": "TLS 1.0 supported (deprecated)", "severity": "medium"},
    ]

    crawl_json = {
        "meta": {
            "target": target_url,
            "spider": "synthetic-fallback",
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "note": "Generated by CyTrack fallback (spider binary not installed)",
        },
        "summary": {
            "total_endpoints": len(endpoints),
            "header_issues": len(header_audit),
            "secrets": 0,
            "sensitive_files_found": 0,
            "graphql_exposed": 0,
            "openapi_exposed": 0,
            "waf_detected": False,
        },
        "endpoints": endpoints,
        "target_response_headers": {
            "Server": "nginx",
            "Content-Type": "text/html",
        },
        "header_audit": header_audit,
        "tech_stack": [],
        "waf_findings": [],
        "secrets": [],
        "graphql": [],
        "openapi": [],
        "sourcemaps": [],
        "sensitive_files": [],
        "js_libs": [],
        "dns_findings": [],
        "cors_issues": [],
        "credentials": [],
        "extracted_data": [],
        "comments": [],
        "tls_findings": tls_findings,
        "robots_disallowed": [],
        "robots_allowed": [],
        "js_orphan_params": [],
        "socketio_endpoints": [],
        "crt_subdomains": [],
        "cloud_probes": [],
        "page_graph": {},
        "agent_targets": [],
        "whatweb_data": [],
    }

    output_path.write_text(json.dumps(crawl_json, indent=2), encoding="utf-8")


async def start_crawl(job: ScanJob) -> None:
    """
    Run HellHound in a worker thread so subprocess execution
    works reliably with FastAPI/Uvicorn on Windows.

    If the spider binary is not installed, falls back to a synthetic crawl
    JSON so the full pipeline (parser -> context builder -> planner -> report)
    can still run and produce real output.
    """
    agent = agents[job.agent_id]

    publish_log(
        agent.id,
        f"[{job.id}] crawler started for {job.target_url}",
    )

    crawl_output = config.crawl_output_for(job.id)

    # ── Check if spider binary is available ──────────────────────────────────
    if not _spider_is_available():
        publish_log(
            agent.id,
            f"[{job.id}] spider binary not found — using synthetic crawl mode",
        )
        publish_log(
            agent.id,
            f"[{job.id}] generating synthetic discovery for {job.target_url}...",
        )

        def write_synthetic():
            _make_synthetic_crawl(job.target_url, crawl_output)

        try:
            await asyncio.to_thread(write_synthetic)
        except Exception as exc:
            job.status = ScanStatus.FAILED
            job.finished_at = time.time()
            agent.status = ScanStatus.FAILED
            publish_log(agent.id, f"[{job.id}] synthetic crawl error: {exc}")
            return

        publish_log(
            agent.id,
            f"[{job.id}] synthetic crawl complete — {crawl_output.name}",
        )

        # Proceed directly to analysis
        await _run_analysis(job, agent, crawl_output)
        return

    # ── Real spider run ──────────────────────────────────────────────────────
    def run_spider() -> int:
        env = os.environ.copy()
        env["PYTHONIOENCODING"] = "utf-8"
        env["PYTHONUTF8"] = "1"

        process = subprocess.Popen(
            [
                _spider_executable(),
                job.target_url,
                "--depth",
                str(job.depth),
                "-o",
                str(crawl_output),
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            env=env,
        )

        assert process.stdout is not None

        for line in process.stdout:
            current_job = scans.get(job.id)

            if (
                current_job is None
                or current_job.status != ScanStatus.RUNNING
            ):
                publish_log(
                    agent.id,
                    f"[{job.id}] crawler stopping...",
                )

                process.terminate()

                try:
                    process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait()

                return process.returncode or 0

            text = line.strip()

            if text:
                publish_log(
                    agent.id,
                    f"[{job.id}] {text}",
                )

        return process.wait()

    try:
        return_code = await asyncio.to_thread(run_spider)

        if job.status == ScanStatus.STOPPED:
            return

        job.finished_at = time.time()

        if return_code == 0:
            publish_log(
                agent.id,
                f"[{job.id}] crawler completed",
            )
            await _run_analysis(job, agent, crawl_output)

        else:
            job.status = ScanStatus.FAILED
            agent.status = ScanStatus.FAILED

            publish_log(
                agent.id,
                f"[{job.id}] crawler failed with code {return_code}",
            )

    except Exception as exc:
        job.status = ScanStatus.FAILED
        job.finished_at = time.time()
        agent.status = ScanStatus.FAILED

        publish_log(
            agent.id,
            f"[{job.id}] crawler error: "
            f"{type(exc).__name__}: {repr(exc)}",
        )


async def _run_analysis(job: ScanJob, agent, crawl_output: Path) -> None:
    """Run the analysis pipeline after crawl data is ready."""
    try:
        from core.pipeline import run_analysis

        await asyncio.to_thread(run_analysis, job, crawl_output)
    except Exception as exc:  # noqa: BLE001 - analysis is best-effort
        publish_log(
            agent.id,
            f"[{job.id}] analysis error: "
            f"{type(exc).__name__}: {repr(exc)}",
        )

    job.status = ScanStatus.COMPLETED
    job.finished_at = time.time()
    agent.status = ScanStatus.COMPLETED
    publish_log(agent.id, f"[{job.id}] scan complete")